#!/usr/bin/tclsh

set f [open "data2.dat" w]

# Random number with normal distribution
# https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform
proc nrand {} {
  return  [expr sqrt(-2.0 * log(rand()))*cos(2*3.1415926*rand())]
}

for {set i 0} {$i<400} {incr i} {
  incr x
  set r [nrand]
  set y [expr sin(2*3.1415926*$x/100) + 0.2*$r]
  puts $f "$x $y"
}

for {set i 0} {$i<200} {incr i} {
  incr x
  puts $f "$x [expr 0.2*[nrand]]"
}

for {set i 0} {$i<200} {incr i} {
  incr x
  if {$i == 100} {puts $f "$x 0"}\
  else {puts $f "$x [expr 0.2*[nrand] + 3]"}
}

for {set i 0} {$i<200} {incr i} {
  incr x
  set r [nrand]
  if {$i < 100} {puts $f "$x [expr $i/100.0+0.2*[nrand]]"}\
  else {puts $f "$x [expr 1+0.2*[nrand]]"}
}

incr x
puts $f "$x 0"
incr x
puts $f "$x 0"
