#!/usr/bin/tclsh

# Test filter without using graphene.
# read file, run filter command, print data to stdout

foreach f [glob ../*.tcl] {source $f}

if {$::argc != 1} {
  error "usage: test_simple <filter command> < <data_in> > <data_out>"
}
set cmd [lindex $::argv 0]

set storage {}
foreach l [split [read stdin] '\n'] {
  set time [lindex $l 0]
  set data [lreplace $l 0 0]

  if {[eval $cmd]} {puts "$time $data"}
}