#!/bin/sh -efu

# Test input filter by creating a database, setting the filter,
# putting datafile to the db, printing values from the db.
# Double values are used.

if [ "${1:-}" == "" ]; then
  printf "Usage: test_ifilter <filter> < <idata> > <odata>\n"
  exit 1
fi

filter=$1

gr="../../graphene -E none -d . -T .."
dbname=ifilter
dtype=DOUBLE

$gr delete $dbname &> /dev/null ||:
$gr create $dbname $dtype
$gr set_filter $dbname 0 "$filter"

while read l; do
  echo put_flt $dbname $l
done | $gr -i | grep '#Error' 1>&2 ||:

$gr get_range $dbname
$gr delete $dbname

