#!/usr/bin/perl
#example of perl filter

# set up buffering
select((select(STDOUT), $|=1)[0]);

# read line by line
while (my $line = <STDIN>){
  my ($t, $v1, $v2) = split(/\s+/, $line);
  $v = $v1 + $v2;
  print "$t $v1 $v2 $v\n";
}
