#!/bin/sh -efu

name=graphene
ver=2.13

tag=
DIR="$name-$ver"

rm -rf -- "$DIR"
mkdir "$DIR"
cd "$DIR"

git clone ../../ .
[ ! -d modules ] || git submodule init
[ "$tag" = "" ]  || git checkout --detach $tag
[ ! -d modules ] || git submodule update

[ ! -d modules ] || rm -f modules.tar update_modules
rm -rf .git .gear

mv -f graphene_http.init.ubuntu graphene_http.init

mkdir debian
for f in changelog control copyright rules; do
  sed 's/${ver}/'$ver'/g' ../$f > debian/$f
done

dpkg-buildpackage --build=any

cd ..
rm -rf -- "$DIR"
